defaults: &defaults
  host: localhost
  persist_in_safe_mode: true
  allow_dynamic_fields: false
  use_activesupport_time_zone: true

development:
  <<: *defaults
  database: developments_development

test:
  <<: *defaults
  database: developments_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
