defaults: &defaults
  host: localhost
  persist_in_safe_mode: true
  allow_dynamic_fields: false
  use_activesupport_time_zone: true
  embedded_object_id: false

development:
  <<: *defaults
  database: developments_development

test:
  <<: *defaults
  database: developments_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
