defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: developments_development

test:
  <<: *defaults
  database: developments_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
